import torch
from rl4co.envs import TSPEnv
from tensordict import TensorDict
import os

def generate_tsplib(
    num_nodes=100000,
    batch_size=1,
    area_size=100.0,
    save_dir="./tsplib_outputs",
    prefix="TSP"
):
    """
    Generate TSP instances with RL4CO and export to TSPLIB format.
    """
    os.makedirs(save_dir, exist_ok=True)

    # Create env with custom generator parameters
    env = TSPEnv(
        generator_params={
            "num_loc": num_nodes,
            "min_loc": 0.0,
            "max_loc": area_size,      # area_size × area_size map
        }
    )

    # --- 1) Generate instances ---
    batch = env.generator._generate(batch_size=(batch_size,))
    locs = batch["locs"]  # shape = [batch_size, num_nodes, 2]

    # --- 2) Save each instance as TSPLIB ---
    paths = []
    for b in range(batch_size):
        coords = locs[b].cpu().numpy()

        filename = os.path.join(
            save_dir,
            f"{prefix}_{num_nodes}_{b+1}.tsp"
        )
        paths.append(filename)

        with open(filename, "w") as f:
            f.write(f"NAME : {prefix}_{b+1}\n")
            f.write(f"COMMENT : Generated by RL4CO\n")
            f.write("TYPE : TSP\n")
            f.write(f"DIMENSION : {num_nodes}\n")
            f.write("EDGE_WEIGHT_TYPE : EUC_2D\n")
            f.write("NODE_COORD_SECTION\n")

            for i, (x, y) in enumerate(coords, start=1):
                f.write(f"{i} {x:.6f} {y:.6f}\n")

            f.write("EOF\n")

    return paths


# ----------------------------
# Example usage
# ----------------------------
if __name__ == "__main__":
    files = generate_tsplib(
        num_nodes=50_000,   # large-scale TSP
        batch_size=4,       # generate 2 instances
        area_size=10000.0,  # coordinates in [0, 10000]
        save_dir="./my_tsps",
        prefix="BIGTSP"
    )
    print("Generated files:", files)
